name: Fetch Events

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: .ruby-version

    - name: Install dependencies
      run: bundle install

    - name: Fetch events
      run: bundle exec ruby fetch-events.rb > all-events.ical

    - name: Commit and push changes
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git add .
        if ! git diff --staged --quiet; then
          git commit -m "Update events"
          git push
        fi